selected_environment: dev

dev:
    database:
        name: babywonder_dev
        host: localhost
        port: 3306
        username: root
        password: ""
    authfile: /path/to/dev_authfile.pem
    port: 8080

prod:
    database:
        name: prod_db
        host: prod.example.com
        port: 5432
        username: prod_user
        password: prod_password
    authfile: /path/to/prod_authfile.pem
    port: 8080
